### ISSUE TITLE
Re-write API to be more RESTful

### ISSUE THREAD

**Issue by rlunger** [ft-january-2019/final-project#20]
Currently our REST API is inconsistent. GET on a /files/{id} or /folders/{id} should return metadata about those resources. There is also no consistent way to trash and delete file and folder resources. We would like to propose a redesign of the API.

**Comment by rlunger** [comment]
This is our proposed fix:

# Endpoint documentation

This document details the endpoints exposed on the service written for the final project of the January 2019 FT class.
These endpoints are used for communication between the server and client of our project.

## File Endpoints:
---
|         URL        | METHOD |               Description               |                       Request                        |               Success                |                                  Failure                                  |
|:------------------:|:------:|:---------------------------------------:|:----------------------------------------------------:|:------------------------------------:|:-------------------------------------------------------------------------:|
| /files             |  POST  | Upload a file and save it on the server | Body: { name: string, data: string, folder: string } | Status: 201 Body: { fileId: number } | Status: 400 ; 409 Body: {  message: error uploading file }                |
| /files             | DELETE | Delete multiple files                   | Body: {  ids: [number]  }                            | Status: 200                          | Status: 400 ; 403 Body: { message: File not in trash. };404 Body: { message: Files not in trash } |
| /files             | PATCH  | Update multiple files                   | Body: [ {id: number, fields to update } ]            | Status: 200 | Status: 400 ; 404 Body: { message: Files not found. } ; 409 Body: { message: Naming conflict. } |
| /files/:id/download|   GET  | Download a single file                  |                                                      | Status: 200 Body: file   | Status: 404 Body: { message: Could not download file. File not found }    |
| /files/:id         |  GET   | Get file info                           |   | Status: 200 Body: fileObject | Status: 404 Body: { message: File not found. } |
| /files/:id         |  PATCH | Update a file                           | Body: { folderId: number, isTrash: boolean, name: string } | Status: 200                          | Status: 400 ; 404 ; 409 Body: { message: naming conflict. }               |
| /files/:id         | DELETE | Delete a single file                    |                                                      | Status: 200                          | Status: 403 Body: { message: File not in trash. }; 404 Body: { message: File not found. }      |

## Folder Endpoints:
---
|          URL         | METHOD |            Description             |        Request         |                                                                       Success                                                                        |                                   Failure                                   |
|:--------------------:|:------:|:----------------------------------:|:----------------------:|:----------------------------------------------------------------------------------------------------------------------------------------------------:|:---------------------------------------------------------------------------:|
| /folders             |  POST  | Create a folder                    | Body: { name: string } | Status: 201 Body: { folderId: number }                                                                                                               | Status: 400 ; 409 Body: {  message: error creating the folder }             |
| /folders             | DELETE | Delete multiple folders            | Body: { ids: [number] }| Status: 200                                                                                                                                          | Status: 400 ; 403 Body: { message: Folders not in trash. }; 404 Body: { folders not found } |    
| /folders             | PATCH  | Updates multiple folders           | Body: [ {id: number, fields to update }] | Status: 200 | Status: 400 ; 404 Body: {message: Folders not found. } ; 409 Body: { message: Naming conflict } |                                                                                                                                        
| /folders/:id         | DELETE | Delete a single folder             |                        | Status: 200                                                                                                                                          | Status: 400 ; 403 Body: { message: Folder not in trash. }; 404 Body: { message: There was an issue deleting the folder } |
| /folders/:id         |   GET  | Get folder info            |                        | Status: 200 Body: { created: datetime, name: string, id: number, files: [{   id: number,   name: string,   folder: string,    created: datetime  }}] | Status: 404 Body: { message: Could not download folder. Folder not found }  |
| /folders/:id         | PATCH  | Updates a folder                   | Body: { name: string, isTrash: boolean } | Status: 200 Body: folderObject | Status: 400 ; 404 ; 409 Body: {message: naming conflict. }|
| /folders/:id/download| GET    | Download a  folder                |                        | Status: 200 Body:  zip-file | Status: 404 Body: { message: Folder not found. }
| /folders/root        |   GET  | Get everything in the root folder  |                        | Status: 200Body: { files: [fileObject], folders: [folderObject] }                                                                                    |                                                                             |
| /folders/trash       |   GET  | Get everything in the trash folder |                        | Status: 200 Body: { files: [fileObject], folders: [folderObject] }                                                                                   |                                                                             |
| /folders/trash       | DELETE | Delete everything in trash        |                        | Status: 200                                                                                                                                          |                    |

**Comment by wmarttala** [comment]
Looks good to me. Just as an aside, you can have more controllers than entities. They don't have to line up one-to-one. For example, you could add a trash controller that handles things in the trash. That way instead of /folder/trash it would just be /trash. Also, getting all files and folders just through the folder endpoint is kind of odd. I would recommend breaking it down into GET /files to get all non-deleted files and GET /folders to get all non-deleted folders. However, this isn't strictly necessary. You could also just have another endpoint like /all or /root in its own controller to get all non-deleted files and folders in the top level directory.

**Comment by wmarttala** [comment]
@ft-january-2019/client
