### ISSUE TITLE
Design the data model

### ISSUE THREAD

**Issue by wmarttala** [ft-january-2019/final-project#3]
Students need to create an ERD for their database. This should also be maintained somewhere and updated throughout the project before changes are made to the actual database.

**Comment by wmarttala** [comment]
Check out this site [ERD site](https://online.visual-paradigm.com/)

**Comment by cagborgli** [comment]
![ERD](https://user-images.githubusercontent.com/16801342/54559499-3121e780-498e-11e9-9edc-e5cf320bc341.png)
